### ISSUE TITLE
Create second IGV.xml with HTTP URLs

### ISSUE THREAD

**Issue by smondet** [hammerlab/epidisco#1]

**Comment by ihodes** [comment]
Should be URLs to the items hosted in the Google Bucket

**Comment by ihodes** [comment]
superseded by https://github.com/hammerlab/epidisco/issues/15

**Comment by smondet** [comment]
Why is #15 superseding this?

We could create an `IGV.xml` with just one parameter: the URL prefix the user wants; so no need to depend on google-buckets.

**Comment by ihodes** [comment]
I suppose we could do this, but it's a pretty general solution that we already have (don't think it relies on buckets per se). The IGV.xml just points to relative paths, so as long as the files are in the position they are found in in the final-results directory, this works. I might be overlooking a need we have aside from that?
