### ISSUE TITLE
epidisco (web) preprint

### ISSUE THREAD

**Issue by c1ndygao** [hammerlab/epidisco#110]
@c1ndygao commented on [Thu Dec 08 2016](https://github.com/hammerlab/hammerlab.github.io/issues/163)

@iskandr @ihodes @armish ???

**Comment by armish** [comment]
Issue moved to [hammerlab/epidisco-web #23](https://github.com/hammerlab/epidisco-web/issues/23) via [**ZenHub**](https://www.zenhub.com/)
