### ISSUE TITLE
Get NetMHCCons working for Vaxrank

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#12]
Using the "random" predictor is not exactly what we want.

**Comment by ihodes** [comment]
@armish tentatively assigning you if you're still interested. We don't _need_ this to work for the general case; this can be a fix that works just for our pipeline for now (as getting NetMHCCons working for just us in the pipeline seems way more tractable using something like our netmhc bundle).

**Comment by armish** [comment]
@ihodes: I am on it :+1: (related: https://github.com/hammerlab/biokepi/issues/287)

**Comment by ihodes** [comment]
Awesome, thank you! If the Biokepi implementation is crazy, it's definitely most important that it just works internally for our Epidisco/PGV pipeline for now.
