### ISSUE TITLE
disco.sh ketrew-ui uses old IP after new IP assigned

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/epidisco#153]
When I restart my VM and get a new IP, `./disco.sh ketrew-ui` still tells me to go to the old IP because it's pulling in my `configuration.env`, which has `export EXTERNAL_IP=...`.

**Comment by hammer** [comment]
@armish notes that `/tmp/coclo/_kclient_config/configuration.ml` needs to be updated as well.
