### ISSUE TITLE
Add topiary to the pipeline

### ISSUE THREAD

**Issue by armish** [hammerlab/epidisco#158]
Given the name/purpose of this pipeline ("Personalized cancer **epitope discovery** and **peptide vaccine prediction** pipeline"), I think we should run topiary by default in addition to vaxrank and include the list of predicted neoepitopes in the results.

**Comment by smondet** [comment]
It is there:  https://github.com/hammerlab/epidisco/blob/0e768f4521853dd635a1783fb1b29fcd1a2ed339/src/lib/parameters.ml#L9
But there is no option to set it to `true` when using command-line submission

**Comment by ihodes** [comment]
+ no use of that parameter, either.

**Comment by ihodes** [comment]
\+ no use of that parameter, either.

**Comment by smondet** [comment]
@ihodes indeed: https://github.com/hammerlab/epidisco/search?utf8=%E2%9C%93&q=topiary
Its use must have been partially removed at some point (I remember adding and running it at some point).

**Comment by smondet** [comment]
This is relevant: https://github.com/hammerlab/epidisco/commit/150579b2ccbe4247b50b7f074cb646ca7c266eca
Does topiary take multiple VCFs now?
