### ISSUE TITLE
Do we want to BQSR before IndelRealign?

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#17]
@dannykwells aught this issue; he's going to post on the forums about it.

Cf. https://software.broadinstitute.org/gatk/best-practices/mutect1.php

Looks like the Broad notes in the diagram here a different order than we follow. 

@iskandr @arahuja

**Comment by arahuja** [comment]
Hm I wonder if this is just because it makes the diagramming easier since some pipelines don't use it? I could've swore it used to be the other way.

**Comment by arahuja** [comment]
Yes the older "retired" best practices did have it the other way: 
http://gatkforums.broadinstitute.org/gatk/discussion/1186/old-version-of-best-practices-from-gatk-2-0-retired

**Comment by ihodes** [comment]
Good to know; thanks for digging that up. I definitely remembered it being the other way around. 

Not sure I see that one way is necessarily right; I buy your first explanation.

**Comment by ihodes** [comment]
Danny posted and got a reply affirming the above http://gatkforums.broadinstitute.org/gatk/discussion/comment/32187#Comment_32187
