### ISSUE TITLE
Document running epidisco w/ coclobas

### ISSUE THREAD

**Issue by hammer** [hammerlab/epidisco#21]
Host docs currently at https://gist.github.com/smondet/a96d6050c865906d699d0e2637f7ced8 in this repo.

**Comment by hammer** [comment]
Here's my command log: https://docs.google.com/document/d/1-ng1qvBywhoiP23mS9l6mLoF00jwnHB2l-Cf1mewmoQ/edit

Sadly I'm getting an error at the very end of the process:

```
Submitting to Ketrew...
[ketrew: ERROR]
   Run-error: Client: HTTP Call (POST
   https:///api?format=json&token=tok � Exn:
   Unix.Unix_error(Unix.ECONNREFUSED, "connect", ""))
run_pipeline.ml: internal error, uncaught exception:
                (Failure
                  "Client: HTTP Call (POST https:///api?format=json&token=tok \226\134\146 Exn: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\"))")
```

**Comment by smondet** [comment]
@hammer:

```
gcloud compute instances create jh-epidisco-launcher --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --zone us-east1-c --scopes cloud-platform --tags default-allow-https
```

It seems that the `--tags` option is not enough https://cloud.google.com/sdk/gcloud/reference/compute/instances/create says:

> Specifies a list of tags to apply to the instances for identifying the instances to which network firewall rules will apply. See gcloud compute firewall-rules create(1) for more details.

I just created an instance with the same command and the HTTPS port is indeed not open.

**Comment by smondet** [comment]
There is the Firewall module in stratocumulus: https://github.com/hammerlab/stratocumulus/blob/master/src/lib/deploy.ml#L846

Not 100% but something like this should do the trick:

```
 gcloud compute firewall-rules create rule-01 --allow tcp:443  --source-tags=default-allow-https --source-ranges 0.0.0.0/0 
```

Replacing the `default-allow-https` tag with the name of the instance would make the rule more local / less side-effect-full.

**Comment by smondet** [comment]
Yeah tested with `$ sudo nc -l 443` and `nc <ip-addr> 443` from another host.

**Comment by smondet** [comment]
Also, all of this is not needed:

```
On the launcher instance, from stratotemplate
sudo apt-get update
sudo apt-get install -y unzip build-essential git emacs
curl https://sdk.cloud.google.com | bash
bash
gcloud config set compute/zone us-east1-c
gcloud compute ssh $(hostname) ls
```

(well except emacs maybe :) )

**Comment by smondet** [comment]
In the clean-up section, the GKE cleanup:

```
gcloud compute instance-groups managed list (to get gke instance group)
gcloud compute instance-groups managed delete gke-jh-epidisco-cluster-default-pool-6c513c01-grp (for example)
```

I don't think it is enough, there is still the cluster from a `kubernetes` point of view.

Use:

```
coclobas cluster --root /coclo/_cocloroot/ delete
```
