### ISSUE TITLE
Simplify running epidisco on GCP

### ISSUE THREAD

**Issue by hammer** [hammerlab/epidisco#23]
Some ideas:
- [ ] Use `gcloud` CLI rather than web UI for launching the "GClouder" instance
- [ ] [Make our own GClouder image](https://cloud.google.com/compute/docs/images/export-image)/have a [startup script](https://cloud.google.com/compute/docs/startupscript) rather than using a base OS image and requiring the user to type commands in "Setup the Host" into the shell
- [ ] Automate the creation of an NFS filer (or, better: have tools pull/push data from/to Google cloud storage so that we don't require an NFS filer!)
- [ ] Automate the edits to `coclobas/master/tools/docker/configuration.env`
- [ ] Pull reference, dbSNP, and other data used by tools from [Google Genomics public data sets](https://cloud.google.com/genomics/v1/public-data)
- [ ] Create `run_pipeline.ml` for the user

**Comment by hammer** [comment]
The first checkbox up there is trivially satisfied with two commands:

```
gcloud compute instances create jh-epidisco-launcher --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --zone us-east1-c
gcloud compute ssh jh-epidisco-launcher
```

**Comment by hammer** [comment]
I think it's totally fine to require the user to have `gcloud` installed and configured; we can point them to https://cloud.google.com/sdk/downloads for the instructions.

**Comment by smondet** [comment]
@hammer your command is missing the access to the GCloud API, something like `--scope compute-rw,...`

**Comment by hammer** [comment]
@smondet thanks think `cloud-platform` is broader so will try that out

**Comment by hammer** [comment]
Nice this worked!

```
gcloud compute instances create jh-epidisco-launcher --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --zone us-east1-c --scopes cloud-platform
```

**Comment by hammer** [comment]
Probably going to need to open port 443, think I can just add `--tags default-allow-https`?

New command:

```
gcloud compute instances create jh-epidisco-launcher --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --zone us-east1-c --scopes cloud-platform --tags default-allow-https
```

**Comment by ihodes** [comment]
`--boot-disk-size 50GB` to bump up from default 10
