### ISSUE TITLE
Accept gs:// paths

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#6]
Storing public or private data in a bucket in lieu of a NFS filer is nice; we should support this input type.

**Comment by smondet** [comment]
How could we enable that without loosing portability of Epidisco itself (which not tied to gcloud at all so far)?

**Comment by ihodes** [comment]
I think it's fair that Biokepi support gs:// and https:// paths to input

**Comment by hammer** [comment]
Yeah we could just parse the URI and dispatch to the appropriate storage handler as is done e.g. in HDFS

**Comment by ihodes** [comment]
This is fixed in Biokepi https://github.com/hammerlab/biokepi/pull/326

**Comment by smondet** [comment]
@ihodes it doesn't take `gs://` URLs though (the code to do it would be easy; getting a shell environment where `gsutil` works is more annoying).

**Comment by ihodes** [comment]
Good point; it supports HTTPS, though, which is really what I meant by this issue 🍤

**Comment by julia326** [comment]
Reopening this one: it'd be very helpful for using private data from buckets, which we can't get over HTTPS right now.

**Comment by ihodes** [comment]
Fixed in https://github.com/hammerlab/biokepi/pull/405
