### ISSUE TITLE
Can't run kubectl from within the docker container 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#61]
$ kubectl logs b89fd949-9032-5eae-9689-XXXXXXXXX
The connection to the server 104.196.xx.xxxx was refused - did you specify the right host or port?

**Comment by smondet** [comment]
Is this consistent or does it work at some point?
Looks like the usual google-cloud unreliability.

**Comment by ihodes** [comment]
Running it today I get the expected "Error from server: pods "b89fd949-9032-5eae-9689-8f230061409f" not found"

**Comment by ihodes** [comment]
This is due to having too many SSH keys (too much metadata).  Deleting some of those resolved this. http://stackoverflow.com/questions/36375030/kubectl-error-from-server-no-ssh-tunnels-currently-open
