### ISSUE TITLE
Update the pipeline to do PDF report generation

### ISSUE THREAD

**Issue by julia326** [hammerlab/epidisco#93]
and pin to a new version of vaxrank, which has self-peptide filtering and (soon-to-be) assembly fixes.

**Comment by ihodes** [comment]
Biokepi is where the change will mostly go (though will need to do a minor update of the pipeline here, too) https://github.com/hammerlab/biokepi/issues/367

**Comment by julia326** [comment]
What worked on a gcloud instance:

wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
tar xvfJ wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
cd bin
sudo chown root:root wkhtmltopdf 
sudo cp wkhtmltopdf /usr/local/bin/wkhtmltopdf
then: make a ~/.fonts.conf with the contents at http://pastebin.com/AmfYN3er for the kerning to not be awful

**Comment by julia326** [comment]
@ihodes this one's ready for you now - should just need to bump the pinned `vaxrank` version and change the arguments so that the call looks like:

```
vaxrank \
    --vcf <mutect> --vcf <strelka> \
    --bam <rna> \
    --mhc-predictor netmhccons \
    --mhc-alleles <alleles> \
    --vaccine-peptide-length 25 \
    --padding-around-mutation 5 \
    --max-vaccine-peptides-per-mutation 3 \
    --max-mutations-in-report 20 \
    --min-mapping-quality 1 \
    --min-variant-sequence-coverage 1 \
    --min-alt-rna-reads 3 \
    --mhc-epitope-lengths 8,9,10,11 \
    --output-patient-id <id> \
    --output-reviewed-by 'Alex Rubinsteyn,Isaac Hodes,Julia Kodysh' \
    --output-final-review 'Alex Rubinsteyn' \
    --output-ascii-report <ascii> \
    --output-pdf-report <pdf> \
    --output-xlsx-report <xlsx>
```
